/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/early-access': typeof EarlyAccessRoute
  '/faq': typeof FaqRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/early-access': typeof EarlyAccessRoute
  '/faq': typeof FaqRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/early-access': typeof EarlyAccessRoute
  '/faq': typeof FaqRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/collection'
    | '/contact'
    | '/early-access'
    | '/faq'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/size-guide'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/collection'
    | '/contact'
    | '/early-access'
    | '/faq'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/size-guide'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/collection'
    | '/contact'
    | '/early-access'
    | '/faq'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/size-guide'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  FaqRoute: typeof FaqRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SizeGuideRoute: typeof SizeGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  FaqRoute: FaqRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SizeGuideRoute: SizeGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
